name: Deploy Firebase Functions

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    name: Deploy Firebase Backend
    runs-on: ubuntu-latest
    env:
          FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ vars.FIREBASE_STORAGE_BUCKET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
          NODE_ENV: ${{ vars.NODE_ENV }}
          PORT: ${{ vars.PORT }}
          PREFIX: ${{ vars.PREFIX }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: rebuild TypeScript
        run: npm rebuild typescript
      - name: Build TypeScript
        run: npm run build
      - name: Install latest Firebase CLI
        run: npm install -g firebase-tools@latest
      
      - name: Configure Google credentials
        run: |
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' > $HOME/service-account.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/service-account.json" >> $GITHUB_ENV
          ls -l $HOME/service-account.json
      - name: Deploy to Firebase
        run: |
          echo "✅ Environment variables loaded:"
          echo "Project: $FIREBASE_PROJECT_ID"
          echo "Bucket: $FIREBASE_STORAGE_BUCKET"
          echo "Prefix: $PREFIX"
          firebase deploy --only functions --project $FIREBASE_PROJECT_ID --non-interactive --force --debug